// Code generated by internal/generate/main.go. DO NOT EDIT.

package ramctx

import (
	"context"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/ram"
	"github.com/aws/aws-sdk-go/service/ram/ramiface"
	"github.com/glassechidna/awsctx"
)

type RAM interface {
	AcceptResourceShareInvitationWithContext(ctx context.Context, input *ram.AcceptResourceShareInvitationInput, opts ...request.Option) (*ram.AcceptResourceShareInvitationOutput, error)
	AssociateResourceShareWithContext(ctx context.Context, input *ram.AssociateResourceShareInput, opts ...request.Option) (*ram.AssociateResourceShareOutput, error)
	CreateResourceShareWithContext(ctx context.Context, input *ram.CreateResourceShareInput, opts ...request.Option) (*ram.CreateResourceShareOutput, error)
	DeleteResourceShareWithContext(ctx context.Context, input *ram.DeleteResourceShareInput, opts ...request.Option) (*ram.DeleteResourceShareOutput, error)
	DisassociateResourceShareWithContext(ctx context.Context, input *ram.DisassociateResourceShareInput, opts ...request.Option) (*ram.DisassociateResourceShareOutput, error)
	EnableSharingWithAwsOrganizationWithContext(ctx context.Context, input *ram.EnableSharingWithAwsOrganizationInput, opts ...request.Option) (*ram.EnableSharingWithAwsOrganizationOutput, error)
	GetResourcePoliciesWithContext(ctx context.Context, input *ram.GetResourcePoliciesInput, opts ...request.Option) (*ram.GetResourcePoliciesOutput, error)
	GetResourceShareAssociationsWithContext(ctx context.Context, input *ram.GetResourceShareAssociationsInput, opts ...request.Option) (*ram.GetResourceShareAssociationsOutput, error)
	GetResourceShareInvitationsWithContext(ctx context.Context, input *ram.GetResourceShareInvitationsInput, opts ...request.Option) (*ram.GetResourceShareInvitationsOutput, error)
	GetResourceSharesWithContext(ctx context.Context, input *ram.GetResourceSharesInput, opts ...request.Option) (*ram.GetResourceSharesOutput, error)
	ListPrincipalsWithContext(ctx context.Context, input *ram.ListPrincipalsInput, opts ...request.Option) (*ram.ListPrincipalsOutput, error)
	ListResourcesWithContext(ctx context.Context, input *ram.ListResourcesInput, opts ...request.Option) (*ram.ListResourcesOutput, error)
	RejectResourceShareInvitationWithContext(ctx context.Context, input *ram.RejectResourceShareInvitationInput, opts ...request.Option) (*ram.RejectResourceShareInvitationOutput, error)
	TagResourceWithContext(ctx context.Context, input *ram.TagResourceInput, opts ...request.Option) (*ram.TagResourceOutput, error)
	UntagResourceWithContext(ctx context.Context, input *ram.UntagResourceInput, opts ...request.Option) (*ram.UntagResourceOutput, error)
	UpdateResourceShareWithContext(ctx context.Context, input *ram.UpdateResourceShareInput, opts ...request.Option) (*ram.UpdateResourceShareOutput, error)
}

type Client struct {
	ramiface.RAMAPI
	Contexter awsctx.Contexter
}

func New(base ramiface.RAMAPI, ctxer awsctx.Contexter) RAM {
	return &Client{
		RAMAPI: base,
		Contexter: ctxer,
	}
}

var _ RAM = (*ram.RAM)(nil)
var _ RAM = (*Client)(nil)

func (c *Client) AcceptResourceShareInvitationWithContext(ctx context.Context, input *ram.AcceptResourceShareInvitationInput, opts ...request.Option) (*ram.AcceptResourceShareInvitationOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "AcceptResourceShareInvitationWithContext",
		Input:   input,
		Output:  (*ram.AcceptResourceShareInvitationOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.AcceptResourceShareInvitationWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.AcceptResourceShareInvitationOutput), req.Error
}

func (c *Client) AssociateResourceShareWithContext(ctx context.Context, input *ram.AssociateResourceShareInput, opts ...request.Option) (*ram.AssociateResourceShareOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "AssociateResourceShareWithContext",
		Input:   input,
		Output:  (*ram.AssociateResourceShareOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.AssociateResourceShareWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.AssociateResourceShareOutput), req.Error
}

func (c *Client) CreateResourceShareWithContext(ctx context.Context, input *ram.CreateResourceShareInput, opts ...request.Option) (*ram.CreateResourceShareOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "CreateResourceShareWithContext",
		Input:   input,
		Output:  (*ram.CreateResourceShareOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.CreateResourceShareWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.CreateResourceShareOutput), req.Error
}

func (c *Client) DeleteResourceShareWithContext(ctx context.Context, input *ram.DeleteResourceShareInput, opts ...request.Option) (*ram.DeleteResourceShareOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "DeleteResourceShareWithContext",
		Input:   input,
		Output:  (*ram.DeleteResourceShareOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.DeleteResourceShareWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.DeleteResourceShareOutput), req.Error
}

func (c *Client) DisassociateResourceShareWithContext(ctx context.Context, input *ram.DisassociateResourceShareInput, opts ...request.Option) (*ram.DisassociateResourceShareOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "DisassociateResourceShareWithContext",
		Input:   input,
		Output:  (*ram.DisassociateResourceShareOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.DisassociateResourceShareWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.DisassociateResourceShareOutput), req.Error
}

func (c *Client) EnableSharingWithAwsOrganizationWithContext(ctx context.Context, input *ram.EnableSharingWithAwsOrganizationInput, opts ...request.Option) (*ram.EnableSharingWithAwsOrganizationOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "EnableSharingWithAwsOrganizationWithContext",
		Input:   input,
		Output:  (*ram.EnableSharingWithAwsOrganizationOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.EnableSharingWithAwsOrganizationWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.EnableSharingWithAwsOrganizationOutput), req.Error
}

func (c *Client) GetResourcePoliciesWithContext(ctx context.Context, input *ram.GetResourcePoliciesInput, opts ...request.Option) (*ram.GetResourcePoliciesOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "GetResourcePoliciesWithContext",
		Input:   input,
		Output:  (*ram.GetResourcePoliciesOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.GetResourcePoliciesWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.GetResourcePoliciesOutput), req.Error
}

func (c *Client) GetResourceShareAssociationsWithContext(ctx context.Context, input *ram.GetResourceShareAssociationsInput, opts ...request.Option) (*ram.GetResourceShareAssociationsOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "GetResourceShareAssociationsWithContext",
		Input:   input,
		Output:  (*ram.GetResourceShareAssociationsOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.GetResourceShareAssociationsWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.GetResourceShareAssociationsOutput), req.Error
}

func (c *Client) GetResourceShareInvitationsWithContext(ctx context.Context, input *ram.GetResourceShareInvitationsInput, opts ...request.Option) (*ram.GetResourceShareInvitationsOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "GetResourceShareInvitationsWithContext",
		Input:   input,
		Output:  (*ram.GetResourceShareInvitationsOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.GetResourceShareInvitationsWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.GetResourceShareInvitationsOutput), req.Error
}

func (c *Client) GetResourceSharesWithContext(ctx context.Context, input *ram.GetResourceSharesInput, opts ...request.Option) (*ram.GetResourceSharesOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "GetResourceSharesWithContext",
		Input:   input,
		Output:  (*ram.GetResourceSharesOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.GetResourceSharesWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.GetResourceSharesOutput), req.Error
}

func (c *Client) ListPrincipalsWithContext(ctx context.Context, input *ram.ListPrincipalsInput, opts ...request.Option) (*ram.ListPrincipalsOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "ListPrincipalsWithContext",
		Input:   input,
		Output:  (*ram.ListPrincipalsOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.ListPrincipalsWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.ListPrincipalsOutput), req.Error
}

func (c *Client) ListResourcesWithContext(ctx context.Context, input *ram.ListResourcesInput, opts ...request.Option) (*ram.ListResourcesOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "ListResourcesWithContext",
		Input:   input,
		Output:  (*ram.ListResourcesOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.ListResourcesWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.ListResourcesOutput), req.Error
}

func (c *Client) RejectResourceShareInvitationWithContext(ctx context.Context, input *ram.RejectResourceShareInvitationInput, opts ...request.Option) (*ram.RejectResourceShareInvitationOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "RejectResourceShareInvitationWithContext",
		Input:   input,
		Output:  (*ram.RejectResourceShareInvitationOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.RejectResourceShareInvitationWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.RejectResourceShareInvitationOutput), req.Error
}

func (c *Client) TagResourceWithContext(ctx context.Context, input *ram.TagResourceInput, opts ...request.Option) (*ram.TagResourceOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "TagResourceWithContext",
		Input:   input,
		Output:  (*ram.TagResourceOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.TagResourceWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.TagResourceOutput), req.Error
}

func (c *Client) UntagResourceWithContext(ctx context.Context, input *ram.UntagResourceInput, opts ...request.Option) (*ram.UntagResourceOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "UntagResourceWithContext",
		Input:   input,
		Output:  (*ram.UntagResourceOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.UntagResourceWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.UntagResourceOutput), req.Error
}

func (c *Client) UpdateResourceShareWithContext(ctx context.Context, input *ram.UpdateResourceShareInput, opts ...request.Option) (*ram.UpdateResourceShareOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "ram",
		Action:  "UpdateResourceShareWithContext",
		Input:   input,
		Output:  (*ram.UpdateResourceShareOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.RAMAPI.UpdateResourceShareWithContext(ctx, input, opts...)
	})

	return req.Output.(*ram.UpdateResourceShareOutput), req.Error
}
