// Code generated by internal/generate/main.go. DO NOT EDIT.

package fmsctx

import (
	"context"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/fms"
	"github.com/aws/aws-sdk-go/service/fms/fmsiface"
	"github.com/glassechidna/awsctx"
)

type FMS interface {
	AssociateAdminAccountWithContext(ctx context.Context, input *fms.AssociateAdminAccountInput, opts ...request.Option) (*fms.AssociateAdminAccountOutput, error)
	DeleteNotificationChannelWithContext(ctx context.Context, input *fms.DeleteNotificationChannelInput, opts ...request.Option) (*fms.DeleteNotificationChannelOutput, error)
	DeletePolicyWithContext(ctx context.Context, input *fms.DeletePolicyInput, opts ...request.Option) (*fms.DeletePolicyOutput, error)
	DisassociateAdminAccountWithContext(ctx context.Context, input *fms.DisassociateAdminAccountInput, opts ...request.Option) (*fms.DisassociateAdminAccountOutput, error)
	GetAdminAccountWithContext(ctx context.Context, input *fms.GetAdminAccountInput, opts ...request.Option) (*fms.GetAdminAccountOutput, error)
	GetComplianceDetailWithContext(ctx context.Context, input *fms.GetComplianceDetailInput, opts ...request.Option) (*fms.GetComplianceDetailOutput, error)
	GetNotificationChannelWithContext(ctx context.Context, input *fms.GetNotificationChannelInput, opts ...request.Option) (*fms.GetNotificationChannelOutput, error)
	GetPolicyWithContext(ctx context.Context, input *fms.GetPolicyInput, opts ...request.Option) (*fms.GetPolicyOutput, error)
	GetProtectionStatusWithContext(ctx context.Context, input *fms.GetProtectionStatusInput, opts ...request.Option) (*fms.GetProtectionStatusOutput, error)
	ListComplianceStatusWithContext(ctx context.Context, input *fms.ListComplianceStatusInput, opts ...request.Option) (*fms.ListComplianceStatusOutput, error)
	ListComplianceStatusPagesWithContext(ctx context.Context, input *fms.ListComplianceStatusInput, cb func(*fms.ListComplianceStatusOutput, bool) bool, opts ...request.Option) error
	ListMemberAccountsWithContext(ctx context.Context, input *fms.ListMemberAccountsInput, opts ...request.Option) (*fms.ListMemberAccountsOutput, error)
	ListMemberAccountsPagesWithContext(ctx context.Context, input *fms.ListMemberAccountsInput, cb func(*fms.ListMemberAccountsOutput, bool) bool, opts ...request.Option) error
	ListPoliciesWithContext(ctx context.Context, input *fms.ListPoliciesInput, opts ...request.Option) (*fms.ListPoliciesOutput, error)
	ListPoliciesPagesWithContext(ctx context.Context, input *fms.ListPoliciesInput, cb func(*fms.ListPoliciesOutput, bool) bool, opts ...request.Option) error
	ListTagsForResourceWithContext(ctx context.Context, input *fms.ListTagsForResourceInput, opts ...request.Option) (*fms.ListTagsForResourceOutput, error)
	PutNotificationChannelWithContext(ctx context.Context, input *fms.PutNotificationChannelInput, opts ...request.Option) (*fms.PutNotificationChannelOutput, error)
	PutPolicyWithContext(ctx context.Context, input *fms.PutPolicyInput, opts ...request.Option) (*fms.PutPolicyOutput, error)
	TagResourceWithContext(ctx context.Context, input *fms.TagResourceInput, opts ...request.Option) (*fms.TagResourceOutput, error)
	UntagResourceWithContext(ctx context.Context, input *fms.UntagResourceInput, opts ...request.Option) (*fms.UntagResourceOutput, error)
}

type Client struct {
	fmsiface.FMSAPI
	Contexter awsctx.Contexter
}

func New(base fmsiface.FMSAPI, ctxer awsctx.Contexter) FMS {
	return &Client{
		FMSAPI: base,
		Contexter: ctxer,
	}
}

var _ FMS = (*fms.FMS)(nil)
var _ FMS = (*Client)(nil)

func (c *Client) AssociateAdminAccountWithContext(ctx context.Context, input *fms.AssociateAdminAccountInput, opts ...request.Option) (*fms.AssociateAdminAccountOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "AssociateAdminAccount",
		Input:   input,
		Output:  (*fms.AssociateAdminAccountOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.AssociateAdminAccountWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.AssociateAdminAccountOutput), req.Error
}

func (c *Client) DeleteNotificationChannelWithContext(ctx context.Context, input *fms.DeleteNotificationChannelInput, opts ...request.Option) (*fms.DeleteNotificationChannelOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "DeleteNotificationChannel",
		Input:   input,
		Output:  (*fms.DeleteNotificationChannelOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.DeleteNotificationChannelWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.DeleteNotificationChannelOutput), req.Error
}

func (c *Client) DeletePolicyWithContext(ctx context.Context, input *fms.DeletePolicyInput, opts ...request.Option) (*fms.DeletePolicyOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "DeletePolicy",
		Input:   input,
		Output:  (*fms.DeletePolicyOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.DeletePolicyWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.DeletePolicyOutput), req.Error
}

func (c *Client) DisassociateAdminAccountWithContext(ctx context.Context, input *fms.DisassociateAdminAccountInput, opts ...request.Option) (*fms.DisassociateAdminAccountOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "DisassociateAdminAccount",
		Input:   input,
		Output:  (*fms.DisassociateAdminAccountOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.DisassociateAdminAccountWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.DisassociateAdminAccountOutput), req.Error
}

func (c *Client) GetAdminAccountWithContext(ctx context.Context, input *fms.GetAdminAccountInput, opts ...request.Option) (*fms.GetAdminAccountOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "GetAdminAccount",
		Input:   input,
		Output:  (*fms.GetAdminAccountOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.GetAdminAccountWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.GetAdminAccountOutput), req.Error
}

func (c *Client) GetComplianceDetailWithContext(ctx context.Context, input *fms.GetComplianceDetailInput, opts ...request.Option) (*fms.GetComplianceDetailOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "GetComplianceDetail",
		Input:   input,
		Output:  (*fms.GetComplianceDetailOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.GetComplianceDetailWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.GetComplianceDetailOutput), req.Error
}

func (c *Client) GetNotificationChannelWithContext(ctx context.Context, input *fms.GetNotificationChannelInput, opts ...request.Option) (*fms.GetNotificationChannelOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "GetNotificationChannel",
		Input:   input,
		Output:  (*fms.GetNotificationChannelOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.GetNotificationChannelWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.GetNotificationChannelOutput), req.Error
}

func (c *Client) GetPolicyWithContext(ctx context.Context, input *fms.GetPolicyInput, opts ...request.Option) (*fms.GetPolicyOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "GetPolicy",
		Input:   input,
		Output:  (*fms.GetPolicyOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.GetPolicyWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.GetPolicyOutput), req.Error
}

func (c *Client) GetProtectionStatusWithContext(ctx context.Context, input *fms.GetProtectionStatusInput, opts ...request.Option) (*fms.GetProtectionStatusOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "GetProtectionStatus",
		Input:   input,
		Output:  (*fms.GetProtectionStatusOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.GetProtectionStatusWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.GetProtectionStatusOutput), req.Error
}

func (c *Client) ListComplianceStatusWithContext(ctx context.Context, input *fms.ListComplianceStatusInput, opts ...request.Option) (*fms.ListComplianceStatusOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "ListComplianceStatus",
		Input:   input,
		Output:  (*fms.ListComplianceStatusOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.ListComplianceStatusWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.ListComplianceStatusOutput), req.Error
}

func (c *Client) ListComplianceStatusPagesWithContext(ctx context.Context, input *fms.ListComplianceStatusInput, cb func(*fms.ListComplianceStatusOutput, bool) bool, opts ...request.Option) error {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "ListComplianceStatus",
		Input:   input,
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Error = c.FMSAPI.ListComplianceStatusPagesWithContext(ctx, input, cb, opts...)
	})

	return req.Error
}

func (c *Client) ListMemberAccountsWithContext(ctx context.Context, input *fms.ListMemberAccountsInput, opts ...request.Option) (*fms.ListMemberAccountsOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "ListMemberAccounts",
		Input:   input,
		Output:  (*fms.ListMemberAccountsOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.ListMemberAccountsWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.ListMemberAccountsOutput), req.Error
}

func (c *Client) ListMemberAccountsPagesWithContext(ctx context.Context, input *fms.ListMemberAccountsInput, cb func(*fms.ListMemberAccountsOutput, bool) bool, opts ...request.Option) error {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "ListMemberAccounts",
		Input:   input,
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Error = c.FMSAPI.ListMemberAccountsPagesWithContext(ctx, input, cb, opts...)
	})

	return req.Error
}

func (c *Client) ListPoliciesWithContext(ctx context.Context, input *fms.ListPoliciesInput, opts ...request.Option) (*fms.ListPoliciesOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "ListPolicies",
		Input:   input,
		Output:  (*fms.ListPoliciesOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.ListPoliciesWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.ListPoliciesOutput), req.Error
}

func (c *Client) ListPoliciesPagesWithContext(ctx context.Context, input *fms.ListPoliciesInput, cb func(*fms.ListPoliciesOutput, bool) bool, opts ...request.Option) error {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "ListPolicies",
		Input:   input,
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Error = c.FMSAPI.ListPoliciesPagesWithContext(ctx, input, cb, opts...)
	})

	return req.Error
}

func (c *Client) ListTagsForResourceWithContext(ctx context.Context, input *fms.ListTagsForResourceInput, opts ...request.Option) (*fms.ListTagsForResourceOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "ListTagsForResource",
		Input:   input,
		Output:  (*fms.ListTagsForResourceOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.ListTagsForResourceWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.ListTagsForResourceOutput), req.Error
}

func (c *Client) PutNotificationChannelWithContext(ctx context.Context, input *fms.PutNotificationChannelInput, opts ...request.Option) (*fms.PutNotificationChannelOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "PutNotificationChannel",
		Input:   input,
		Output:  (*fms.PutNotificationChannelOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.PutNotificationChannelWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.PutNotificationChannelOutput), req.Error
}

func (c *Client) PutPolicyWithContext(ctx context.Context, input *fms.PutPolicyInput, opts ...request.Option) (*fms.PutPolicyOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "PutPolicy",
		Input:   input,
		Output:  (*fms.PutPolicyOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.PutPolicyWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.PutPolicyOutput), req.Error
}

func (c *Client) TagResourceWithContext(ctx context.Context, input *fms.TagResourceInput, opts ...request.Option) (*fms.TagResourceOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "TagResource",
		Input:   input,
		Output:  (*fms.TagResourceOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.TagResourceWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.TagResourceOutput), req.Error
}

func (c *Client) UntagResourceWithContext(ctx context.Context, input *fms.UntagResourceInput, opts ...request.Option) (*fms.UntagResourceOutput, error) {
	req := &awsctx.AwsRequest{
		Service: "fms",
		Action:  "UntagResource",
		Input:   input,
		Output:  (*fms.UntagResourceOutput)(nil),
		Error:   nil,
	}

	ctxer := c.Contexter
	if ctxer == nil {
		ctxer = awsctx.NoopContexter
	}

	ctxer.WrapContext(ctx, req, func(ctx context.Context) {
		req.Output, req.Error = c.FMSAPI.UntagResourceWithContext(ctx, input, opts...)
	})

	return req.Output.(*fms.UntagResourceOutput), req.Error
}
