name: Check upstream for new SDK

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  upstream:
    name: Upstream
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -d ./...

      - name: Generate
        run: ./generate.sh

      - name: Commit files
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: ./bump.sh
